### ISSUE TITLE
Application.css file missing

### ISSUE THREAD

**Issue by iwaffles** [maccman/holla#4]
The application.css file seems to be missing.

**Comment by maccman** [comment]
It's generated by Less

**Comment by lolomarx** [comment]
But the Less can't generate it on my enviroment.   ... I use ruby192 -p180 ,rails 3.0.5
Any suggestion?

**Comment by maccman** [comment]
Any errors when less tries to generate it?

On Sat, Mar 26, 2011 at 10:07 PM, lolomarx <
reply@reply.github.com>wrote:

> But the Less can't generate it on my enviroment.   ... I use ruby192 -p180
> ,rails 3.0.5
> Any suggestion?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/holla/issues/4#comment_919917

## 

Alex MacCaw

(415) 513-0975
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by lolomarx** [comment]
Can't see any error message. i will prefer to have the default file then less can genereate and replace it to avoid compatibility issues. Any way i will try your holla 2 first and learn from it. Thx

**Comment by sebouh** [comment]
I'm having the same problem. There is no less.js file in the page source.  There's also an error loading application.css shown below.  

Started GET "/ria" for 127.0.0.1 at 2011-03-28 23:33:02 -0700
  Processing by RiaController#index as HTML
  User Load (0.1ms)  SELECT `users`.\* FROM `users` WHERE (`users`.`id` = 'd788deab24755e7a624fca69bf') ORDER BY created_at ASC LIMIT 1
  CACHE (0.0ms)  SELECT `users`.\* FROM `users` WHERE (`users`.`id` = 'd788deab24755e7a624fca69bf') ORDER BY created_at ASC LIMIT 1
Rendered ria/index.html.erb (2.1ms)
Completed 200 OK in 96ms (Views: 3.6ms | ActiveRecord: 0.2ms)

Started GET "/stylesheets/application.css" for 127.0.0.1 at 2011-03-28 23:33:02 -0700
[2011-03-28 23:33:04] ERROR NoMethodError: undefined method `each' for #<String:0x00000005f14b90>
    /home/user/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.1/lib/rack/handler/webrick.rb:64:in`service'
    /home/user/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
    /home/user/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/httpserver.rb:70:in`run'
    /home/user/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'

Started GET "/javascripts/application.js" for 127.0.0.1 at 2011-03-28 23:33:04 -0700

Started GET "/ria/loader?_=1301380384694" for 127.0.0.1 at 2011-03-28 23:33:04 -0700
  Processing by RiaController#loader as JSON
  Parameters: {"_"=>"1301380384694"}
  User Load (0.1ms)  SELECT `users`.\* FROM `users` WHERE (`users`.`id` = 'd788deab24755e7a624fca69bf') ORDER BY created_at ASC LIMIT 1
  CACHE (0.0ms)  SELECT `users`.\* FROM `users` WHERE (`users`.`id` = 'd788deab24755e7a624fca69bf') ORDER BY created_at ASC LIMIT 1
  Channel Load (0.6ms)  SELECT `channels`.\* FROM `channels` INNER JOIN `user_channels` ON `channels`.id = `user_channels`.channel_id WHERE ((`user_channels`.user_id = 'd788deab24755e7a624fca69bf')) ORDER BY created_at ASC
Completed 200 OK in 195ms (Views: 0.7ms | ActiveRecord: 6.9ms)

**Comment by maccman** [comment]
You need to be using Thin as a webserver:

```
rails server thin
```
